// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKjBKvjl5oDRyyGFVKTqrTxo_pAE_PVlk',
    appId: '1:636820893822:web:7f6358542ee4ebff19282f',
    messagingSenderId: '636820893822',
    projectId: 'provaandre-75e2c',
    authDomain: 'provaandre-75e2c.firebaseapp.com',
    storageBucket: 'provaandre-75e2c.firebasestorage.app',
    measurementId: 'G-MEXN0S4SRT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDot6YC2CKP3UzttEYg9OrVuLH6zcm9cJQ',
    appId: '1:636820893822:android:ccc7841d56578c0319282f',
    messagingSenderId: '636820893822',
    projectId: 'provaandre-75e2c',
    storageBucket: 'provaandre-75e2c.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKjBKvjl5oDRyyGFVKTqrTxo_pAE_PVlk',
    appId: '1:636820893822:web:c944a9fc6e8dad6219282f',
    messagingSenderId: '636820893822',
    projectId: 'provaandre-75e2c',
    authDomain: 'provaandre-75e2c.firebaseapp.com',
    storageBucket: 'provaandre-75e2c.firebasestorage.app',
    measurementId: 'G-D9823KCVBM',
  );

}